

<div class="rk-product">
<div class="gridblocktwee">
    <ul>
        <li>Ingebruikname: 01 januari 2011</li>
        <li>Voorziening: <a href="__RELEASEKALENDERBOUWSTEEN__basisregistratie-waarde-onroerende-zaken-woz">Basisregistratie Waarde onroerende zaken (<abbr title="Waarde Onroerende Zaken">WOZ</abbr>)</a></li>
		<li>Aanbieder: Softwareleveranciers</li>
		<li>Doelgroep: Gemeenten</li>
	                <li>Verwijzing: <a class="external_link" href="http://www.waarderingskamer.nl/basisregistratie-woz-lv-woz/aansluiten-gemeenten-lvwoz/">Gemeentelijke <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties</a></li>
	        </ul>
    <p>De bestaande <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties geven functionaliteit voor beheer van Basisregistratie <abbr title="Waarde Onroerende Zaken">WOZ</abbr>, inclusief vervaardiging brondocumenten (aanslagbiljetten) etc. Deze applicaties moeten relaties naar <abbr title="Gemeentelijke Basisadministratie Personen">GBA</abbr>, Kadaster, Handelsregister en <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr> ondersteunen. Deze relaties moeten ook in de <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-administratie (Gegevensverzameling <abbr title="Waarde Onroerende Zaken">WOZ</abbr>) worden vastgelegd. Vanuit deze gemeentelijke applicatie worden ook de afnemers (Belastingdienst, waterschappen, <abbr title="Centraal Bureau voor de Statistiek">CBS</abbr> en ook nieuwe afnemers zoals notariaat, banken) geinformeerd. Nu verloopt dit informeren direct door elke gemaante afzonderlijk naar de afnemers. Na aansluiting van de gemeentelijke <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties op de <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr>, hoeft er vanuit de gemeentelijke <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicatie geen informatie te gaan naar afnemers. De gemeente is zelf verantwoordelijk voor de <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicatie waarmee men werkt. Er zijn diverse softwareleveranciers waar men een dergelijke applicatie kan verkrijgen. De eisen aan deze applicatie betreffen met name de output van de systemen, zoals de gegevenslevering aan afnemers, de aansluiting op <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr> etc. Verder is er onderlinge concurrentie tussen softwareleveranciers op het terrein van gebruiksvriendelijkheid, ondersteuning werkstromen en beheersingsmaatregelen, etc.</p>	<h2>Gerealiseerde releases</h2>
		    	    <h3 id="gemeentelijke-woz-applicaties-voorziet-in-aansluiten-op-lv-woz">Gemeentelijke <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties voorziet in aansluiten op <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr></h3>
	    <ul>
	        <li>Gerealiseerd op 01 juli 2014</li>
		    <li>Verwijzing: <a class="external_link" href="http://www.waarderingskamer.nl/basisregistratie-woz-lv-woz/aansluiten-gemeenten-lvwoz/">Gemeentelijke <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties voorziet in aansluiten op <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr></a></li>
<li>Releasestatus: Gerealiseerd</li>
		    	<li>Aandachtspunten: <p>Om een gemeentelijke <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicatie te mogen gebruiken voor aansluiting op de Landelijke Voorziening <abbr title="Waarde Onroerende Zaken">WOZ</abbr> (<abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr>), moet deze applicatie de conformiteitstoets met goed gevolg hebben afgerond. De <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr> biedt sinds april 2013 de functionaliteit voor het afnemen van deze conformiteitstoets.</p>
<p>Per 1 juli 2014 hebben de belangrijkste gemeentelijke <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties deze conformiteitstoets met goed gevolg afgelegd.</p></li>
		    	    </ul>
		<p><abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties zijn technisch in staat om gegevens aan te leveren aan de <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr>, op basis van <abbr title="Standaard Uitwisselings Formaat">StUF</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr> 03.12 (Berichtcatalogus <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr>) en digikoppeling. Dit betekent ook dat deze <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties in staat zijn om de <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr>-gegevens op een correctie wijze te koppelen aan <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-objecten (en <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-deelobjecten). Wanneer een gemeentelijke <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties wordt aangesloten op de <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr>, moet voldaan zijn aan alle eisen die samenhangen met de Catalogus Basisregistratie <abbr title="Waarde Onroerende Zaken">WOZ</abbr>, Catalogus <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-gegevens voor afnemers en Berichtcatalogus <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr> binnen <abbr title="Standaard Uitwisselings Formaat">StUF</abbr> woz 03.12. Dit betekent onder andere:</p>
<ul><li>het correct relateren van de diverse <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr>-objecten aan <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-objecten (<abbr title="Waarde Onroerende Zaken">WOZ</abbr>-deelobjeten);</li>
<li>het werken op basis van de in de catalogi gespecificeerde gebeurtenissen;</li>
<li>het conform <abbr title="Standaard Uitwisselings Formaat">StUF</abbr> verzenden en verwerken van berichten gespecificeerd in de berichtencatalogus <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr>;</li>
<li>het koppelen aan digikoppeling.</li>
</ul>		<h4>Afhankelijkheden</h4>
		<p><em>Geen afhankelijkheden</em></p>	    <h4>Afspraken en standaarden</h4>
	    <ul><li>Doorleveren <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr>-gegevens</li><li>Gebruik Digikoppeling</li></ul>	    	    <h3 id="gemeentelijke-woz-applicaties-jan-2011">Gemeentelijke <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties - jan 2011</h3>
	    <ul>
	        <li>Gerealiseerd op 01 januari 2011</li>
		    <li>Verwijzing: <a class="external_link" href="http://www.waarderingskamer.nl/basisregistratie-woz-lv-woz/aansluiten-gemeenten-lvwoz/">Gemeentelijke <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties - jan 2011</a></li>
<li>Releasestatus: Gerealiseerd</li>
		    	    </ul>
		<p>Gemeenten beschikken sinds 1995 over applicaties die de uitvoering van de Wet <abbr title="Waarde Onroerende Zaken">WOZ</abbr> ondersteunen. Deze applicaties zijn echter continu in ontwikkeling door ontwikkelingen in de omgeving en door verandering van eisen die aan deze applicaties worden gesteld. Naast de ontwikkeling van applicaties is ook van belang dat gemeenten keuzevrijheid hebben voor de selectie van een leverancier. Ook bij gelijkblijvende eisen, wisselen gemeenten regelmatig van <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicatie, omdat zij een nieuwe aanbesteding doen voor de <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicatie. Er zijn diverse <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties op de markt van verschillende softwareleveranciers. Gemeenten zijn vrij om één van de applicaties te kiezen. Er zijn wel standaard eisen aan de wijze waarop vanuit deze applicaties gegevens worden geleverd aan de afnemers (Belastingdienst, waterschappen en <abbr title="Centraal Bureau voor de Statistiek">CBS</abbr>).</p>		<h4>Afhankelijkheden</h4>
		<p><em>Geen afhankelijkheden</em></p>	    <h4>Afspraken en standaarden</h4>
	    <ul><li>Doorleveren <abbr title="Basisregistratie Kadaster">BRK</abbr>-gegevens</li><li>Doorleveren <abbr title="Gemeentelijke Basisadministratie Personen">GBA</abbr>-gegevens</li></ul>	    	</div>
<div class="gridblocktwee moduletablelinks">
    <h2>Aankomende releases</h2>
    	    		    <h3 id="woz-applicaties-leveren-gegevens-aan-lv-woz"><abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties leveren gegevens aan <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr></h3>
		    <p class="releasedatum">01 oktober 2016, 2-6 maanden marge</p>
<ul>
		        <li>Verwijzing: <a class="external_link" href="http://www.waarderingskamer.nl/basisregistratie-woz-lv-woz/aansluiten-gemeenten-lvwoz/"><abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties leveren gegevens aan <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr></a></li>
	<li>Releasestatus: Gepland</li>
	<li>Aandachtspunten: <p>De gemeentelijke <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties zijn inmiddels geslaagd voor de conformiteitstoets.</p>
<p>Met deze applicaties zijn inmiddels tien gemeenten aangesloten.</p></li>
</ul>
		    <p>Alle gemeentelijke <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties leveren gegevens uit de gegevensverzameling <abbr title="Waarde Onroerende Zaken">WOZ</abbr> aan de <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr>. De <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr> is volledig gevuld. De gemeentelijke <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicatie levert geen <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-gegevens meer aan externe afnemers. Deze afnemers ontvangen hun gegevens uitsluitend vanuit de <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr>. Om te kunnen aansluiten op de <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr> moet de gemeente:</p>
<ul><li>kunnen communiceren op basis van digikoppeling;</li>
<li>de relatie met de <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr>-objecten in de administratie vastgelegd hebben;</li>
<li>beschikken over een <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicatie die de conformiteitstoets goed heeft doorstaan;</li>
<li>een aansluittoets hebben gedaan.</li>
</ul><h4>Afhankelijkheden</h4>
<ul><li>Gegevensverzameling BR <abbr title="Waarde Onroerende Zaken">WOZ</abbr> - Relatie met <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr> gereed</li><li>Gemeentelijke <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-applicaties voorziet in aansluiten op <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr></li></ul>		    <h4>Afspraken en standaarden</h4>
		    <ul><li>Gebruik Digikoppeling</li><li>Relaties <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr>-objecten</li><li>Relaties <abbr title="Basisregistratie Kadaster">BRK</abbr>-objecten</li><li>Relaties <abbr title="Gemeentelijke Basisadministratie Personen">GBA</abbr>-objecten</li><li>Relaties <abbr title="Nieuw Handelsregister">NHR</abbr>-objecten</li></ul>	    	</div>
</div>