

<div class="rk-product">
<div class="gridblocktwee">
    <ul>
        <li>Ingebruikname: 01 januari 2011</li>
        <li>Voorziening: <a href="__RELEASEKALENDERBOUWSTEEN__basisregistratie-waarde-onroerende-zaken-woz">Basisregistratie Waarde onroerende zaken (<abbr title="Waarde Onroerende Zaken">WOZ</abbr>)</a></li>
		<li>Aanbieder: Gemeenten</li>
		<li>Doelgroep: Gemeenten en geautoriseerde afnemers BR <abbr title="Waarde Onroerende Zaken">WOZ</abbr>, zoals Belastingdienst, <abbr title="Centraal Bureau voor de Statistiek">CBS</abbr>, waterschappen</li>
	                <li>Verwijzing: <a class="external_link" href="http://www.waarderingskamer.nl/basisregistratie-woz-lv-woz/documentatie-lvwoz/">BR <abbr title="Waarde Onroerende Zaken">WOZ</abbr> Gegevensverzameling</a></li>
	        </ul>
    <p>De gegevensverzameling voor de Basisregistratie <abbr title="Waarde Onroerende Zaken">WOZ</abbr> bestaat naast het authentieke gegeven "vastgestelde waarde" (<abbr title="Waarde Onroerende Zaken">WOZ</abbr>-waarde) uit de gegevens die nodig zijn om deze waarde aan zowel een onroerende zaak te relateren als aan een belanghebbende. Voor het relateren van de <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-waarde aan een onroerende zaak is er enerzijds de (van een <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr>-adres afgeleide) aanduiding van een onroerende zaak en anderzijds de koppeling aan kadastrale percelen en/of adressen en aan <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr> verblijfsobjecten, standplaatsen, ligplaatsen en/of panden. Verder wordt vastgelegd voor welke belanghebbende de <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-waarde van betekenis is. De NAW-gegevens van deze belanghebbende zijn vastgelegd mede door een relatie naar de <abbr title="Gemeentelijke Basisadministratie Personen">GBA</abbr> of het Handelsregister. Er zijn ook belanghebbenden die niet in één van deze registraties zijn vastgelegd.     Bronhouder: De gemeenten zijn bronhouder van de <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-gegevens binnen de betreffende gemeente. De bronhouders zijn verantwoordelijk voor de opname van gegevens in de registratie en voor de kwaliteit daarvan.</p>	<h2>Gerealiseerde releases</h2>
		    	    <h3 id="gegevensverzameling-br-woz-relatie-met-bag-eerste-fase">Gegevensverzameling BR <abbr title="Waarde Onroerende Zaken">WOZ</abbr> - Relatie met <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr> eerste fase</h3>
	    <ul>
	        <li>Gerealiseerd op 01 januari 2012</li>
		    <li>Verwijzing: <a class="external_link" href="http://www.waarderingskamer.nl/basisregistratie-woz-lv-woz/documentatie-lvwoz/">Gegevensverzameling BR <abbr title="Waarde Onroerende Zaken">WOZ</abbr> - Relatie met <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr> eerste fase</a></li>
<li>Releasestatus: Gerealiseerd</li>
		    	    </ul>
		<ul><li>De aanduidingen van de <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-objecten zijn afgestemd op de formele adressen in de <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr>;</li>
<li>Er is een koppeltabel tussen <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-objecten en <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr>-objecten met name voor de grootschalige belanghebbenden, zoals woningcorporaties.</li>
</ul>
<p>Bij circa 85 % van de gemeenten waren begin 2012 de aanduidingen van de <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-object conform de <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr>-adressen.</p>
<p>Bij circa 40% van de gemeenten was de koppeling met de <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr>-id's ook opvraagbaar voor belanghebbenden.</p>
<p>deel van de <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-objecten kan een <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr>-adres direct worden gebruiks als aanduiding. Voor een ander deel van de <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-objecten is een nadere aanduiding nodig, bijvoorbeeld omdat het <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-object slechts een deel van een verblijfobject betreft. Ook is het mogelijk dat een <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr>-adres in combinatie met en andere aanduiding wordt gebruikt, terwijl het desbetreffende verblijfsobject uit de <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr> geen onderdeel uitmaakt van het <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-object. Ook zijn er aanduidingen van <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-objecten die niet gerelateerd kunnen worden aan een offcieel <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr>-adres (aan een adresseerbaar object). Dit is bijvoorbeld het geval met een weiland.</p>		<h4>Afhankelijkheden</h4>
		<p><em>Geen afhankelijkheden</em></p>	    <h4>Afspraken en standaarden</h4>
	    <ul><li>Relaties <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr>-objecten</li></ul>	    	    <h3 id="gegevensverzameling-br-woz-start-br-woz">Gegevensverzameling BR <abbr title="Waarde Onroerende Zaken">WOZ</abbr> - Start BR <abbr title="Waarde Onroerende Zaken">WOZ</abbr></h3>
	    <ul>
	        <li>Gerealiseerd op 01 januari 2011</li>
		    <li>Verwijzing: <a class="external_link" href="http://www.waarderingskamer.nl/basisregistratie-woz-lv-woz/documentatie-lvwoz/">Gegevensverzameling BR <abbr title="Waarde Onroerende Zaken">WOZ</abbr> - Start BR <abbr title="Waarde Onroerende Zaken">WOZ</abbr></a></li>
<li>Releasestatus: Gerealiseerd</li>
		    	    </ul>
		<p>Bij de start van de Basisregistratie <abbr title="Waarde Onroerende Zaken">WOZ</abbr> bevatte de gegevensverzameling alle onroerende zaken in Nederland met de vastgestelde <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-waarde. De onroerende zaken waren gekoppeld aan de kadastrale percelen en/of kadastrale appartementen. De vastgestelde <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-waarden waren ook gekoppeld aan een belanghebbende. Wanneer die belanghebbende een in Nederland woonachtig natuurlijke persoon is, is in de gegevensverzameling ook de relatie naar de <abbr title="Gemeentelijke Basisadministratie Personen">GBA</abbr> vastgelegd.In de relatie tussen <abbr title="Waarde Onroerende Zaken">WOZ</abbr> en Kadaster vormen de deelpercelen een aandachtspunt. In de periode dat sprake is van deelpercelen, is er vaak sprake van onduidelijkheid over de kadastrale oppervlakte en de status van de verschillende kadastrale objecten.In de relatie naar de <abbr title="Gemeentelijke Basisadministratie Personen">GBA</abbr> vormen de natuurlijke personen die wel belanghebbende zijn, maar geen inwoner zijn van de gemeente, een aandachtspunt.</p>		<h4>Afhankelijkheden</h4>
		<ul><li>AKR bestand (Automatisering Kadastrale Registratie)</li><li><abbr title="Gemeentelijke Basisadministratie Personen">GBA</abbr> Gegevensverzameling 2011</li></ul>	    <h4>Afspraken en standaarden</h4>
	    <ul><li>Relaties <abbr title="Basisregistratie Kadaster">BRK</abbr>-objecten</li><li>Relaties <abbr title="Gemeentelijke Basisadministratie Personen">GBA</abbr>-objecten</li></ul>	    	</div>
<div class="gridblocktwee moduletablelinks">
    <h2>Aankomende releases</h2>
    	    		    <h3 id="gegevensverzameling-br-woz-relatie-met-bag-gereed">Gegevensverzameling BR <abbr title="Waarde Onroerende Zaken">WOZ</abbr> - Relatie met <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr> gereed</h3>
		    <p class="releasedatum">01 oktober 2016, 2-6 maanden marge</p>
<ul>
		        <li>Verwijzing: <a class="external_link" href="http://www.waarderingskamer.nl/basisregistratie-woz-lv-woz/documentatie-lvwoz/">Gegevensverzameling BR <abbr title="Waarde Onroerende Zaken">WOZ</abbr> - Relatie met <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr> gereed</a></li>
	<li>Releasestatus: Gepland</li>
	<li>Aandachtspunten: <p>Deze koppeling moet gereed zijn bij een gemeente, voordat men kan aansluiten op de Landelijke Voorziening <abbr title="Waarde Onroerende Zaken">WOZ</abbr> (<abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr>).</p>
<p>De koppeling met de <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr> verblijfsobjecten (en daarmee adressen) is in nagenoeg alle gemeenten vergevorderd dan wel afgerond. Het koppelen van de "panden zonder verblijfsobject" (bijgebouwen etc.) blijkt in veel gemeenten meet handmatig werk te kosten dan oorspronkelijk gepland. Ook deze koppeling moet (minimaal voor 90%) gereed zijn, voordat een gemeente kan aansluiten op de <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr>.</p>
<p>De definitieve meting of deze koppeling gereed is, vindt plaats wanneer een gemeente aansluit op de <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr>. Daarom is de releasedatum gelijkgetrokken met de releasedatum voor het aansluiten op de <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr>.</p></li>
</ul>
		    <p>In de gemeentelijke gegevensverzameling <abbr title="Waarde Onroerende Zaken">WOZ</abbr> is de relatie tussen <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr> en <abbr title="Waarde Onroerende Zaken">WOZ</abbr> (ook op het niveau) van de <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-deelobjecten volledig gerealiseerd. Deze situatie moet bereikt zijn om te zorgen dat de gemeenten ook kunnen aansluiten op de <abbr title="Landelijke Voorziening">LV</abbr> <abbr title="Waarde Onroerende Zaken">WOZ</abbr>. Om de relatie tussen <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr> en <abbr title="Waarde Onroerende Zaken">WOZ</abbr> beheersbaar te kunen vastleggen, wordt in de gemeentelijke <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-administratie ook gebruik gemaakt van de <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-deelobjecten. Deze <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-deelobjecten worden alleen binnengemeentelijk gebruikt. Aan de afnemers wordt alleen de relatie naar <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr>-objecten verstrekt op het niveau van de <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-objecten (zie Catalogus Basisregistratie <abbr title="Waarde Onroerende Zaken">WOZ</abbr>).</p><h4>Afhankelijkheden</h4>
<p><em>Geen afhankelijkheden</em></p>		    <h4>Afspraken en standaarden</h4>
		    <ul><li>Relaties <abbr title="Basisregistraties Adressen en Gebouwen">BAG</abbr>-objecten</li></ul>	    		    <h3 id="gegevensverzameling-br-woz-relatie-met-handelsregister">Gegevensverzameling BR <abbr title="Waarde Onroerende Zaken">WOZ</abbr> - Relatie met Handelsregister</h3>
		    <p class="releasedatum">01 januari 2017, 6+ maanden marge</p>
<ul>
		        <li>Verwijzing: <a class="external_link" href="http://www.waarderingskamer.nl/basisregistratie-woz-lv-woz/documentatie-lvwoz/">Gegevensverzameling BR <abbr title="Waarde Onroerende Zaken">WOZ</abbr> - Relatie met Handelsregister</a></li>
	<li>Releasestatus: Verwacht</li>
	<li>Aandachtspunten: <p>Ook in 2015 is de vastlegging van <abbr title="Rechtspersonen en Samenwerkingsverbanden Informatie Nummer">RSIN</abbr> bij niet-natuurlijke personen verder geoptimaliseerd. Inmiddels ligt bij de meeste Nederlandse niet-natuurlijke personen in de <abbr title="Waarde Onroerende Zaken">WOZ</abbr>-administratie een <abbr title="Rechtspersonen en Samenwerkingsverbanden Informatie Nummer">RSIN</abbr> vast en wordt deze ook doorgeleverd aan de afnemers (Belastingdienst en waterschappen).</p>
<p>Voor het opvragen en controleren van <abbr title="Rechtspersonen en Samenwerkingsverbanden Informatie Nummer">RSIN</abbr> en andere gegevens uit het Handelsregister maken gemeenten nog primair gebruik van "klassieke" raadpleegvoorzieningen van het Handelsregister.</p>
<p>Realisatie van geautomatiseerde koppelingen zullen naar verwachting ook afhankelijk zijn van de introductie van nieuw <abbr title="Standaard Uitwisselings Formaat">StUF</abbr> bg (03.20) binnen gemeenten.</p></li>
</ul>
		    <p>De relatie in de Gegevensverzameling <abbr title="Waarde Onroerende Zaken">WOZ</abbr> naar een belanghebbende, zijnde een in Nederland gevestigde niet-natuurlijk persoon, is vastgelegd als een relatie naar het Handelsregister. Inclusief een abonnement op de wijzigingen in het Handelsregister met betrekking tot deze niet-natuurlijke persoon. Leggen van relaties met <abbr title="Nieuw Handelsregister">NHR</abbr>-objecten is ook afhankelijk van de releasekalender van de <abbr title="Nieuw Handelsregister">NHR</abbr>. Van belang is het moment waarop gemeenten geautomatiseerd (webservices etc.) het Handelsregister kunnen bevragen en wanneer het mogelijk is op basis van abonnementen informatie te krijgen over alle wijzigingen (gebeurtenissen) met betrekking tot een bepaalde niet-natuurlijke persoon.</p>
<h4>Afhankelijkheden</h4>
<ul><li>Aansluiten Overheid - HR Dataservice (applicatie-applicatie) <abbr title="Standaard Uitwisselings Formaat">StUF</abbr> versie</li></ul>		    <h4>Afspraken en standaarden</h4>
		    <ul><li>Relaties <abbr title="Nieuw Handelsregister">NHR</abbr>-objecten</li></ul>	    		    <h3 id="gegevensverzameling-br-woz-relatie-met-rni">Gegevensverzameling BR <abbr title="Waarde Onroerende Zaken">WOZ</abbr> - Relatie met <abbr title="Registratie Niet Ingezetenen">RNI</abbr></h3>
		    <p class="releasedatum">01 juli 2017, 6+ maanden marge</p>
<ul>
		        <li>Verwijzing: <a class="external_link" href="http://www.waarderingskamer.nl/basisregistratie-woz-lv-woz/documentatie-lvwoz/">Gegevensverzameling BR <abbr title="Waarde Onroerende Zaken">WOZ</abbr> - Relatie met <abbr title="Registratie Niet Ingezetenen">RNI</abbr></a></li>
	<li>Releasestatus: Verwacht</li>
	<li>Aandachtspunten: <p>In 2014 is door de gemeente Texel geprobeerd deze relatie te realiseren. Uit de ervaringen van deze gemeente is geconcludeerd dat deze koppeling uitgesteld moest worden.</p>
<p>Naar verwachting zal ruime implementatie van deze koppeling worden gecombineerd met de implementatie van Operatie <abbr title="Basisregistratie Personen">BRP</abbr>. Daarom is planning bijgesteld.</p></li>
</ul>
		    <p>De relatie in de Gegevensverzameling <abbr title="Waarde Onroerende Zaken">WOZ</abbr> naar een belanghebbende, zijnde een niet-ingezetene natuurlijk persoon, is vastgelegd als een relatie naar de Basisregistratie Personen (Niet-Ingezeten). Inclusief een abonnement op de wijzigingen in het <abbr title="Registratie Niet Ingezetenen">RNI</abbr>.</p><h4>Afhankelijkheden</h4>
<p><em>Geen afhankelijkheden</em></p>		    <h4>Afspraken en standaarden</h4>
		    <ul><li>Relaties <abbr title="Registratie Niet Ingezetenen">RNI</abbr>-objecten</li></ul>	    	</div>
</div>